language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
addons:
  apt:
    packages:
      gradle
before_script:
  - mkdir dependences
  - wget https://github.com/erpcya/adempiere/releases/download/3.9.2-rt-5.0/Adempiere_392LTS.tar.gz  -c -O dependences/Adempiere.tar.gz
script: ./gradlew build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.tar.gz"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.tar.gz.MD5"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.zip"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.zip.MD5"
  skip_cleanup: true
  on:
    tags: true