language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
addons:
  apt:
    packages:
      gradle
script:
  include:
  - stage: Create dependences Dir
  	script: mkdir dependences
  - stage: Main Build
    script: ./gradlew build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.tar.gz"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.tar.gz.MD5"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.zip"
    - "$TRAVIS_BUILD_DIR/adempiere/install/Adempiere_392LTS.zip.MD5"
  skip_cleanup: true
  on:
    tags: true