language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
addons:
  apt:
    packages:
      gradle
before_script:
  - mkdir dependences
  - wget https://github.com/erpcya/adempiere/releases/download/3.9.2-rt-5.0/Adempiere_392LTS.tar.gz  -c -O Adempiere.tar.gz
  - tar --extract --file=Adempiere.tar.gz Adempiere/lib/Adempiere.jar
  - mv Adempiere/lib/Adempiere.jar dependences/Adempiere.jar
script: 
	./gradlew build
	./gradlew jar
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_KEY
  file: 
    - "$TRAVIS_BUILD_DIR/build/libs/Withholding.jar"
  skip_cleanup: true
  on:
    tags: true